//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.EmailServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailServer.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendplayerinfo", ReplyAction="http://tempuri.org/IService1/sendplayerinfoResponse")]
        string sendplayerinfo(string teamid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendplayerinfo", ReplyAction="http://tempuri.org/IService1/sendplayerinfoResponse")]
        System.Threading.Tasks.Task<string> sendplayerinfoAsync(string teamid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendmail", ReplyAction="http://tempuri.org/IService1/sendmailResponse")]
        void sendmail(string reciever, string headline, string content, string playerinfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/sendmail", ReplyAction="http://tempuri.org/IService1/sendmailResponse")]
        System.Threading.Tasks.Task sendmailAsync(string reciever, string headline, string content, string playerinfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Final_Project.EmailServer.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Final_Project.EmailServer.IService1>, Final_Project.EmailServer.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string sendplayerinfo(string teamid) {
            return base.Channel.sendplayerinfo(teamid);
        }
        
        public System.Threading.Tasks.Task<string> sendplayerinfoAsync(string teamid) {
            return base.Channel.sendplayerinfoAsync(teamid);
        }
        
        public void sendmail(string reciever, string headline, string content, string playerinfo) {
            base.Channel.sendmail(reciever, headline, content, playerinfo);
        }
        
        public System.Threading.Tasks.Task sendmailAsync(string reciever, string headline, string content, string playerinfo) {
            return base.Channel.sendmailAsync(reciever, headline, content, playerinfo);
        }
    }
}
