//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.EmailChecker {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmailChecker.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setemail", ReplyAction="http://tempuri.org/IService1/setemailResponse")]
        string setemail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/setemail", ReplyAction="http://tempuri.org/IService1/setemailResponse")]
        System.Threading.Tasks.Task<string> setemailAsync(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Check", ReplyAction="http://tempuri.org/IService1/CheckResponse")]
        bool Check();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Check", ReplyAction="http://tempuri.org/IService1/CheckResponse")]
        System.Threading.Tasks.Task<bool> CheckAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Final_Project.EmailChecker.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Final_Project.EmailChecker.IService1>, Final_Project.EmailChecker.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string setemail(string email) {
            return base.Channel.setemail(email);
        }
        
        public System.Threading.Tasks.Task<string> setemailAsync(string email) {
            return base.Channel.setemailAsync(email);
        }
        
        public bool Check() {
            return base.Channel.Check();
        }
        
        public System.Threading.Tasks.Task<bool> CheckAsync() {
            return base.Channel.CheckAsync();
        }
    }
}
